version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - myapp-data:/var/www/html
    depends_on:
      - mysql
      - phpmyadmin

  mysql:
    container_name: piagenda-mysql-1
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda_bd
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword      
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_USER: myuser
      PMA_PASSWORD: mypassword

volumes:
  myapp-data:
  mysql-data:
